name = "hrweno"
version = "0.1.0"
license = "Apache-2.0 OR MIT"
author = "HugoMVale"
maintainer = "57530119+HugoMVale@users.noreply.github.com"
copyright = "Copyright 2022, HugoMVale"
homepage = "https://github.com/HugoMVale/HR-WENO"
keywords = ["weno", "tvd", "pde"]

[build]
auto-executables = false
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
stdlib = { git = "https://github.com/HugoMVale/stdlib", branch = "stdlib-fpm" }

[dev-dependencies]
test-drive = { git = "https://github.com/zoziha/test-drive", branch = "add-support-array" }

# stdlib = { git = "https://github.com/fortran-lang/stdlib", branch = "stdlib-fpm" }
# fpm test --profile release --flag "-Ofast -ftree-parallelize-loops=2"
