name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        gcc_v: [10] # Version of GFortran we want to use.
        python-version: [3.9]
        include:
        - os: ubuntu-latest
          os-arch: linux-x86_64

    env:
      FC: gfortran
      GCC_V: ${{ matrix.gcc_v }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
   
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
 
    - name: Install Python dependencies
      if: contains( matrix.os, 'ubuntu')
      run: |
        python -m pip install --upgrade pip
        pip install ford
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Install GFortran Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_V} 100 \
        --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${GCC_V} \
        --slave /usr/bin/gcov gcov /usr/bin/gcov-${GCC_V}
    
    - name: Install fpm
      uses: fortran-lang/setup-fpm@v3
      with:
        fpm-version: 'v0.6.0'

    - name: Build with coverage info
      run: |
        gfortran --version
        rm -rf ./build/gfortran*
        fpm test --profile debug --flag --coverage
        gcov ./build/gfortran*/hrweno/src*.gcda -r ./src/ -b -w
               
    - name: Run examples
      run: |
        gfortran --version
        fpm run --profile release --example
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        verbose: true
        
    - name: Build docs with FORD
      run: |
        ford ./api-doc-ford.md
