name: Build and test pkg

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write
  pull-requests: write

jobs:

  test_fpm:
    name: ${{ matrix.os }}_${{ matrix.compiler }}_fpm
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest] # [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gfortran] # [gfortran, lfortran]
        include:
          - os: ubuntu-latest
            compiler: gfortran
            compiler-version: 14.2.0
            extra-packages: ""
          - os: windows-latest
            compiler: gfortran
            compiler-version: 14.2.0
            extra-packages: ""
          
    steps:
      - name: Set up Fortran
        uses: gha3mi/setup-fortran-conda@latest
        with:
          compiler: ${{ matrix.compiler }}
          compiler-version: ${{ matrix.compiler-version }}
          platform: ${{ matrix.os }}
          extra-packages: ${{ matrix.extra-packages }}

      - name: Test debug mode
        run: fpm test --compiler ${{ matrix.compiler }} --profile debug --flag "-fopenmp" --verbose

      - name: Test release mode
        run: fpm test --compiler ${{ matrix.compiler }} --profile release --flag "-fopenmp" --verbose

  # Generate STATUS.md from FPM job results
  status_fpm:
    name: Generate STATUS.md
    if: always()
    needs: test_fpm
    runs-on: ubuntu-latest
    steps:
      - name: Generate summary
        uses: gha3mi/setup-fortran-conda@latest
        with:
          generate-status-fpm: true
